# Generated by Django 4.0.5 on 2022-08-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_delete_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
    ]
