# Generated by Django 4.0.5 on 2022-07-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='img',
            field=models.ImageField(blank=True, default='media/avatares/default', null=True, upload_to='avatares'),
        ),
    ]
