# Generated by Django 4.0.5 on 2022-07-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_avatar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='img',
            field=models.ImageField(blank=True, default='avatares/default.jpg', null=True, upload_to='avatares'),
        ),
    ]
