# Generated by Django 4.0.5 on 2022-07-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('author_id', models.IntegerField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
