# Generated by Django 4.0.5 on 2022-07-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_post_options_remove_post_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='posts/post_default.png', null=True, upload_to='posts'),
        ),
    ]
